db_user: root
db_password: my-secret-pw
db_host: localhost
db_port: 3306
db_name: art
default_time_window_minutes: 60
twitter_bearer_token: AAAAAAAAAAAAAAAAAAAAAD80MwEAAAAAjWjS8JbepyWTt%2Bs6oymg8QhiWQc%3DXwE1IOD1E30qVmi2Gz2dF2xDwCeUiisQxjGlAFfK0EdEcdZ76A
statsapi_host: localhost
